### PR TITLE
Configure renovate to be less noisy:

### PR DESCRIPTION
**Pull request by alexeagle**
- For all dependencies other than Closure compiler:
- update only once a month
- combine all the updates into a single PR

/cc @rarkins to see if I'm doing this right

### CODE REVIEW

**Comment by rarkins** [comment]
@alexeagle I'll get back to you today

**Comment by alexeagle** [comment]
thanks - I didn't see any negative patterns like this in the docs and I don't know how to verify what will be the effect of this change (so it's likely just wrong)

**Comment by rarkins** [comment]
@alexeagle I updated Renovate's logic so that a purely "negating" `packageRule` like you wrote is now valid. I think that's intuitive and others would have the same expectation. I recommend to update it slightly to this though:

```json
{
  "extends": [
    "config:base",
    ":semanticCommitsDisabled"
  ],
  "packageRules": [
    {
      "excludePackageNames": ["google-closure-compiler"],
      "extends": [
        "group:all",
        "schedule:monthly"
      ]
    }
  ],
  "ignorePaths": ["test*/**"]
}
```

This way your monthly PR will be called "Update all packages".

**Comment by alexeagle** [comment]
FYI @mprobst it's possible we'll just get a monthly red PR, and need to dial this back a bit.

**Pull request merged**
