### PR TITLE
Support exported {interface,class,function,variable} declarations.

### PR DESCRIPTION
**Pull request by mprobst**
These already generated appropriate externs symbols, but did not
generate a symbol on the exports object of the module, leading to
Closure Compiler failures when importing the symbol.

This code interprets exported declared symbols as global symbols that
are accessible under the same name, consistent with previous code.
That's somewhat odd though - we could equally well interpret it as
symbols that the user promises should magically appear on the exports
object. This does not really matter for Closure Compiler compatibility
though.

### CODE REVIEW

**Comment by mprobst** [comment]
This might need some more work. Trying it out internally, this will break JS where AJD drops the generated externs. There are also odd issues like:

```ts
export declare interface Foo { x: number; }
export class Foo {}
```

... which leads to the class Foo actually having a `x` defined. People actually do that o_O.

**Comment by evmar** [comment]
Elsewhere in tsickle we do a thing where detect whether there's a type/value conflict and avoid it.
E.g. you can't emit `/** @interface */ var Foo;` on the first Foo because the later class wants to be the value.

**Comment by mprobst** [comment]
Friendly ping.

**Comment by mprobst** [comment]
@evmar is there a way how I can convince you to consider this pull request? Pretty please?

**Comment by mprobst** [comment]
@evmar done wrt copying the folder, PTAL.

**Pull request merged**
