### PR TITLE
feat: add support for TypeScript 3.4

### PR DESCRIPTION
**Pull request by alan-agius4**
//cc @rkirov, @alexeagle & @filipesilva

### CODE REVIEW

**Comment by rkirov** [comment]
Can you commit to a branch for now, so that we don't break g3 during syncing?

**Comment by alan-agius4** [comment]
@rkirov hi, I tried to create a branch `ts_3_4` @ tsickle upstream so that I can target a PR there but I don't have permissions.

**Comment by alexeagle** [comment]
@alan-agius4 I just created https://github.com/angular/tsickle/tree/ts34 branched off current master/HEAD

**Comment by alan-agius4** [comment]
Thanks @alexeagle. Closing this in favor of https://github.com/angular/tsickle/pull/1005

**Pull request closed without merging**
