### PR TITLE
use 'const' for module imports in es6 output mode

### PR DESCRIPTION
**Pull request by evmar**
Emit
  const x = goog.require(...)
instead of
  var x = goog.require(...)

Using 'const' here is semantically more correct (you shouldn't reassign
these anyway) and also forwards type aliases in some circumstances.

### CODE REVIEW

**Comment by evmar** [comment]
Ahh, good catch!

In my experimentation with the original bug it also works to emit a `@const`, like

```
/** @const */
var mod_2 = mod_1;
```

maybe I should just always do that instead?

**Comment by evmar** [comment]
The ES5<->ES6 thing is now fixed.  This includes rebaselines of only the subset of affected tests (the ES6 ones).

**Comment by dsmilkov** [comment]
Any updates on this? Thanks!

**Comment by evmar** [comment]
Oops, I somehow totally dropped this. I gotta test it again against google3 but then I will merge.

**Comment by evmar** [comment]
This works in google3 (with some minor test adjustments), so I'm merging it.

**Pull request merged**
