### PR TITLE
Bump the TypeScript version to 2.9

### PR DESCRIPTION
**Pull request by alippai**

### CODE REVIEW

**Comment by alippai** [comment]
Tried to upgrade as https://github.com/Microsoft/TypeScript/wiki/API-Breaking-Changes didn't show any changes, however it seems there are both in types and behavior. I'm not familiar with the TS Compiler API, so I can't proceed :/

**Comment by evmar** [comment]
That has been our typical experience with upgrading TypeScript versions.  Unfortunately the only answer is to debug and fix it.  We'll probably take on upgrading to 2.9 soon.

**Comment by alippai** [comment]
Updating to TS version 2.9.2 didn't help the regression

**Comment by alippai** [comment]
I think @mprobst added the upgrade today :)

**Comment by mprobst** [comment]
I did, and forgot to reference the right issue here, sorry and thanks for
noticing!

**Pull request closed without merging**
