### PR TITLE
Fix225

### PR DESCRIPTION
**Pull request by hess-g**
#225 - Fixes new lint errors caught in clang 1.0.45.

### CODE REVIEW

**Comment by hess-g** [comment]
@evmar @mprobst PTAL to unblock travis on existing/new PRs.

**Comment by mprobst** [comment]
Did you intend to include two commits in this, or should this be just the clang-format fix?

**Comment by hess-g** [comment]
Should just be the format fix. My git-foo is failing me it seems. Should I rebase this branch?

**Comment by mprobst** [comment]
Yes. Roughly: `git rebase -i upstream/master`, then change the `pick` into
`drop` on the change you don't want, then force push this branch.

**Comment by hess-g** [comment]
Done.

**Pull request merged**
